networks:
  backend_taskApp:
    driver: bridge


services:
  taskDb:
    container_name: personaltasks-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1489:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password1234"
    networks:
        - backend_taskApp


  personaltasks:
    container_name: personaltasks-webapi
    image: ${DOCKER_REGISTRY-}personaltasks
    build:
      context: .
      dockerfile: PersonalTasks/Dockerfile
    ports:
        - "5000:8081"
    depends_on:
      - taskDb
    environment:
     - DB_CONNECTION_STRING=Server=taskDb;Database=TasksDatabase;User Id=sa;Password=Password1234;TrustServerCertificate=True
    networks:
      - backend_taskApp